version: 1.0.{build}
branches:
  only:
  - master
skip_tags: true
build:
  verbosity: minimal
image: Visual Studio 2017
max_jobs: 1
environment:
 global:
  APPVEYOR_CACHE_ENTRY_ZIP_ARGS: "-t7z -m0=lzma -mx=5"
  paperkey:
    secure: MxOJZPR1tTkos0f/z1rM4fjHtWmg4kR3B6uAz8u59R5uDteHyeOSFYwATBPonHVC8oSKAWyrtma2Krk1fIXPMJs+FizIDsxh8VhsgMaeNnU=
  password:
    secure: RjmtameUusXhisMaJSPfbg==
  CPACK_WIX_UPGRADE_GUID_NEON_SERVICE:
    secure: /6AJvIijLn47fUeeEddoPgAE6a9FBYtqEw3qMySIUTuZ5ANkeoBq7p9yUifoznXN
cache:
-  C:\projects\qt-everywhere-opensource-src-4.8.7\ -> appveyor.yml    
build_script:
- cmd: >-
    curl -fsS -o keybase_setup_amd64.msi "https://prerelease.keybase.io/keybase_setup_amd64.msi"
    
    start /wait msiexec.exe /i keybase_setup_amd64.msi   /quiet /l*v keybase.log
    
    curl -fsS -o 7z1900.msi "http://sourceforge.mirrorservice.org/s/se/sevenzip/7-Zip/19.00/7z1900.msi"
    
    start /wait msiexec.exe /i 7z1900.msi  /qb
    
    C:\Python27\python.exe -m pip install cfscrape
    
    C:\Python27\python.exe -m pip install youtube-dl
    
    pip install patch
    
    set PATH=%PATH%;%localappdata%\Keybase\

    keybase -v
    
    REM type keybase.log
    
    echo "loging in to keybase"
    
    ping -n 4 127.0.0.1>nul
    
    call keybase oneshot -u kenkit --paperkey "%paperkey%"
    
    set ROOT=%cd%
    
    cd ../
    
    IF NOT EXIST  "qt-everywhere-opensource-src-4.8.7" 
    (curl  --progress-bar --insecure "https://anonymousfiles.io/f/encrypted_6Ijst7v.cont" -o encrypted.cont && keybase decrypt -i encrypted.cont -o  qt-everywhere-opensource-src-4.8.7_build.zip  && call 7z x qt-everywhere-opensource-src-4.8.7_build.zip)
    
    
    cd qt-everywhere-opensource-src-4.8.7
    
    set QTDIR=%cd%\
    
    cd bin
    
    set QT_BIN=%cd%\
    
    set PATH=%PATH%;%cd%
    
    dir .
    
    set OPENSSL_ROOT_DIR=C:\OpenSSL-Win32\
    
    cd %ROOT%
    
    git config --global --add protocol.keybase.allow always

    git clone keybase://private/kenkit/neon_service 
    
    cd neon_service 
    
    git submodule update --init --recursive

    mkdir build
    
    cd build

    cmake ../ -DCMAKE_BUILD_TYPE=Release -DBOOST_ROOT=C:\Libraries\boost_1_67_0 -DQT_MOC_EXECUTABLE=%QT_BIN%\moc.exe -DQT_RCC_EXECUTABLE=%QT_BIN%\rcc.exe -DQT_UIC_EXECUTABLE=%QT_BIN%\uic.exe -DOTHER_APP=MTK-QTAPP
    
    cmake --build ../build --config Release -j 1
    
    dir .
    
    cd Release

    dir .
    
    curl -fsS -o dll.zip "https://deaddevice.s3-us-west-2.amazonaws.com/dll.zip"
    
    7z.exe x dll.zip -y
    
    del dll.zip
    
    REM del neon_service.exe
    
    cd ../
    
    xcopy C:\projects\neon-service\neon_service\curl\builds\libcurl-vc-x86-release-dll-ipv6-sspi-winssl\bin\*.dll C:\projects\neon-service\neon_service\build\Release\. /Y 
    
    cpack  -C Release
    
test_script:
- cmd: >-
    ctest -VV -C Release -R neon_tests
    
on_finish:
  - ps: (new-object net.webclient).UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path C:\projects\neon-service\neon_service\build\Release\tests.xml))
  
artifacts:
- path: 'neon_service/build/*.msi' 
  name: NeonServiceInstaller-win32.msi
  
before_deploy:
- ps: >-
    echo "NEON SERVICE CHANGELOG"  | Add-Content  -Encoding UTF8 -Path tmp

    echo "************************"  | Add-Content  -Encoding UTF8 -Path tmp

    git log -10   --pretty="%aD--%B" |Add-Content  -Encoding UTF8 -Path tmp

    $currntly=(Resolve-Path .\).Path

    cd $currntly

    $rnp = Resolve-Path("tmp")

    $rnc = [IO.File]::ReadAllText($rnp)

    Set-AppveyorBuildVariable -Name release_description -Value $rnc


  deploy:
- provider: GitHub
  description: $(release_description)
  auth_token:
    secure: qHLbrLphi8zELMch79kGX1wWodd8UQ4nVQDWQAe38W6/ITHJ6S9t50RD6t79DH+O
  repository: kenkit/neon_service
  artifact: NeonServiceInstaller-win32.msi
